stages:
  - build
  - deploy

.docker_build_init_env: &docker_build_init_env |
    if [ -z "$SERVICE_DIR" ]; then export SERVICE_DIR=${CI_JOB_NAME#build-}; fi

.job_docker_build_template: &job_docker_build_definition
  stage: build
  image: docker:latest
  tags: ['docker']
  only: ['master', 'develop']
  when: on_success
  script:
    - *docker_build_init_env
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build-gars:
  <<: *job_docker_build_definition

deploy:
  stage: deploy
  image:
    name: rancher/cli:v0.6.10
    entrypoint: ["/bin/sh", "-c"]
  tags: ['docker']
  only: ['master']
  script:
    - cd .rancher
    - rancher up -d --stack Default --force-upgrade --confirm-upgrade --pull --interval "10000" --batch-size 1
