version: "2"
services:
  gars:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5500:5500
    env_file:
      - .env
    volumes:
      - ./secrets:/secrets
